name: Build and Upload

on:
  pull_request:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: golang:latest
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: run tests
        run: |
          go test
